import { Ubuntu_Sans } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import "aos/dist/aos.js"
import "./globals.css";
import Script from 'next/script'

const inter = Ubuntu_Sans({ weight: '400', subsets: ['latin'] })


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
